<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-N9F7EI8" failures="1" tests="8" name="dbp_Extends_Login.Discount" time="3.297" errors="0" timestamp="2024-05-31T16:03:02 IST" skipped="0">
  <testcase classname="dbp_Extends_Login.Discount" name="Any_Regional_Office_Scheme" time="0.038"/>
  <system-out/>
  <testcase classname="dbp_Extends_Login.Discount" name="Total_Discount_Matches_From_STOCKs" time="1.021">
    <failure message="Values are Invalid = expected [85120941] but found [99747723]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Values are Invalid = expected [85120941] but found [99747723]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:797)
at dbp_Extends_Login.Discount.Total_Discount_Matches_From_STOCKs(Discount.java:176)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:578)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- Total_Discount_Matches_From_STOCKs -->
  <system-out/>
  <testcase classname="dbp_Extends_Login.Discount" name="Consumer_Offer_SPOT_RIPS" time="0.043"/>
  <system-out/>
  <testcase classname="dbp_Extends_Login.Discount" name="Dealer_Discount_Compulsion_Matches_From_STOCKs" time="1.009"/>
  <system-out/>
  <testcase classname="dbp_Extends_Login.Discount" name="Exchange_Bonus" time="0.050"/>
  <system-out/>
  <testcase classname="dbp_Extends_Login.Discount" name="ISL_RMK" time="0.050"/>
  <system-out/>
  <testcase classname="dbp_Extends_Login.Discount" name="Any_Other" time="0.077"/>
  <system-out/>
  <testcase classname="dbp_Extends_Login.Discount" name="Total_Discount" time="1.009"/>
  <system-out/>
</testsuite> <!-- dbp_Extends_Login.Discount -->
